### ISSUE TITLE
Distro

### ISSUE THREAD

**Issue by Faiz-Anjum** [woof-os/qtile#4]
Heyyy, I just wanted to know what distro you are using. Is it Ubuntu or Arch Linux probably?
And do you use it as your primary OS or a dual boot one?

**Comment by ACuteWoof** [comment]
> Heyyy, I just wanted to know what distro you are using. Is it Ubuntu or Arch Linux probably? And do you use it as your primary OS or a dual boot one?

I use Manjaro as my primary OS, and I'll probably stick with it, if I switch, that'll probably be to some Arch based distribution.
It doesn't relate to the config however.

You can contact me on Discord if you want to know me, just send a friend request to `ACuteWoof#7308`
